spring:
  datasource:
    url: jdbc:mysql://47.93.251.190:3306/mysql?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: 47.93.251.190
    port: 6379
    password:
    database: 0
    timeout: 2000
