spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: test
      # 初始化时建立物理连接的个数
      initialSize: 1
      # 最大连接池数量
      maxActive: 20
      # 最小连接池数量
      minIdle: 1
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      maxOpenPreparedStatements: 20
      poolPreparedStatements: true
      # 用来检测连接是否有效的sql
      validationQuery: select 'x'
      # 申请连接的时候检测
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat
      # druid连接池监控
      stat-view-servlet:
        login-username: admin
        login-password: admin
      # 排除静态资源，提高效率
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
mybatis-plus:
  config-location: classpath:mybatis-config.xml
