server:
  port: ${jvm_port:80}
  servlet:
    context-path: /swagger-demo

spring:
  application:
    name: swagger-demo-web
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# log
logging:
  config: classpath:logback-spring.xml