server:
  port: ${jvm_port:80}
  servlet:
    context-path: /redis-demo
spring:
  application:
    name: redis-demo-web
  profiles:
    include: redis-${spring.profiles.active}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    name: /opt/logs/${spring.application.name}/${spring.application.name}.log
