server:
  port: ${jvm_port:80}
  servlet:
    context-path: /mail-demo

spring:
  application:
    name: mail-demo-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    port: 587
    username: liziczh@qq.com
    password: 123456
    default-encoding: UTF-8
    test-connection: false

# log
logging:
  config: classpath:logback-spring.xml