server:
  port: ${jvm_port:80}
  servlet:
    context-path: /mail-demo
# log
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    name: /opt/logs/${spring.application.name}/${spring.application.name}.log
spring:
  application:
    name: mail-demo-web
  profiles:
    active: uat
    include: mail-${spring.profiles.active}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
