server:
  port: ${jvm_port:80}
  servlet:
    context-path: /mail-demo

spring:
  application:
    name: mail-demo-web
  profiles:
    active: uat
    include: mail-${spring.profiles.active}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# log
logging:
  config: classpath:logback-spring.xml