server:
  port: ${jvm_port:80}
  servlet:
    context-path: /redis-demo
spring:
  application:
    name: redis-demo-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 47.93.251.190
    port: 6379
    password:
    database: 0
    timeout: 2000

# log
logging:
  config: classpath:logback-spring.xml
